Fix syntax error using v1.82 interface
Skip non-local trait impl for Iterator & IntoIterator

This is to fix
error: conflicting implementations of trait `T57_IntoIterator` for type `&mut std::boxed::Box<[_], _>`
/.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:351:1
     |
/.rustup/toolchains/1.82.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2329:1

error: conflicting implementations of trait `T55_Iterator` for type `std::boxed::Box<[_], _>`

note: This error was found in Verus pass: ownership checking of tracked code

Only skip trait impl for Box && Adding negative trait in lifetime checking if it is negative trait

Do not skip Box by adding with_negative_coherence

fix write_dep_info

reveret change in builtin_macros/src/syntax

some clean up

revert some